### ISSUE TITLE
Option für Download von Clientprogrammen und settings-Datei einbauen

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#1]
Möglicherweise zwei unterschiedliche Dowloads oder seiten:
* Client-Installer samt auto-generierter config-Datei
* Anleitungsseite zur Anbindung an die ipfire (ggf. auch schon auf die einrichtungsseite - oder schreckt das ab?)

**Comment by TheJKM** [comment]
Added in latest PHP code update
