### ISSUE TITLE
assign profile to new PC automatically

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#11]
assign a new registered PC automatically to a profile if there is a profile with the same name as the room the PC is in

**Comment by TheJKM** [comment]
Added in latest PHP code update, needs updated ClientRegistrationTool for correct message

**Comment by polarwinkel** [comment]
Thanks, I will test it in January when school started and close if working.

**Comment by polarwinkel** [comment]
works, thanks!

**Comment by polarwinkel** [comment]
actually, it did not work when I tried just now.
Let's check that later...

**Comment by polarwinkel** [comment]
Now it works, thanks
