### ISSUE TITLE
Offer a reboot after installation

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#17]
A reboot after Installation should be recommended.

**Comment by TheJKM** [comment]
Done in latest ClientSetup-Update

**Comment by polarwinkel** [comment]
Thanks.
I'll test it the next days.
Was there other stuff to do or can we make a new release with your change?

**Comment by TheJKM** [comment]
I wanted to update OpenSSL to the newest version and maybe remove the DLL-dependency for OpenSSL before release, should be ready next weekend.
