### ISSUE TITLE
schoolTemplatesTeacher-smb-folder not in edit-list

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#18]
The folder does not appear in the list when adding a new folder to a configuration.

It also gets deleted when deleting an other one (in my case one above).

Anyways, is there an easy was to give the Volumes custom names instead of the (english) smb-folder-name?

**Comment by TheJKM** [comment]
To finally solve this a ssh connection from pc_admin (www-data) to samba with permission to modify
- /etc/samba/smb.conf

and run
- service smbd reload
- service nmbd reload

would be very nice. With that working, it would be possible to add / modify all the group folders and their properties from GUI.

**Comment by polarwinkel** [comment]
I just wrote a python-server listening on port 8000 for a http-POST-message, that will be put into the confg and reload the samba.
Do you have the data already put together for the config als multiline-string (with `\n`)? Then I won't need to bother putting it together myself.
Or do you want to send it in json-format?
Whatever you prefer, could you just send me an example of a POST-content you want to send to get an entry like this
```
[SchulTausch]
        path = /home/SchulTausch
        writable = yes

[SchulVorlagen]
        path  /home/SchulVorlagen
        writable = yes
```

**Comment by TheJKM** [comment]
I prefer JSON, as this would make the server more flexible. Then, everything samba-specific is done in it's container. My request (example is in JavaScript) for your two shares above would look like this:
`var params = 'request=' + encodeURIComponent(JSON.stringify(
    [
        {
            name: 'SchulTausch',
            path: '/home/SchulTausch',
            writeable: true,
        },
        {
            name: 'SchulVorlagen',
            path: '/home/SchulVorlagen',
            writeable: true,
        },
    ]
));`
Please keep in mind that there must be a possibility to set the 'valid users' value for restricting access to teachers only, for example:
`var params = 'request=' + encodeURIComponent(JSON.stringify(
    [
        {
            name: 'SchulTausch',
            path: '/home/SchulTausch',
            writeable: true,
            teachers: true,
            students: true,
        },
        {
            name: 'SchulVorlagen',
            path: '/home/SchulVorlagen',
            writeable: true,
            teachers: true,
            students: false,
        },
    ]
));`
would create the following samba config:
`[SchulTausch]
        path = /home/SchulTausch
        writable = yes

[SchulVorlagen]
        path  /home/SchulVorlagen
        writable = yes
        valid users = @teachers`

**Comment by polarwinkel** [comment]
in `dev`-Branch the `samba`-container is now listening on port `8000` for a http-request to change the samba-config.
I tested it with the following curl-command from the `pc_admin`-container:
```
curl -i -X POST -H 'Content-Type: application/json' -d '[ { "name": "SchulTausch", "path": "/home/SchulTausch", "writeable": true, "teachers": true, "students": true}, { "name": "SchulVorlagen", "path": "/home/SchulVorlagen", "writeable": true, "teachers": true, "students": false}]' http://samba:8000 
```
Please be aware that I had to remove the "empty" JSON-parts (the `,` after some data).
The Replacement of `'` by `"` is most likely only for my curl-command necessary.

And: I removed the default-config (see `samba/smbFolders`-file, I will remove that file after all is working), could you send that during the setup?

**Comment by polarwinkel** [comment]
One more thing: in lines 68/69 of `smbFolderChanger.py` I only do a `reload` of the `smbd`-Server, maybe a `force-reload` is necessary (which would most likely kill existing connections though), and `nmbd` can only `force-reload`, I think we don't need that!?

**Comment by TheJKM** [comment]
Thanks, I‘ll integrate and test it. I dont know if a normal reload is enough, but testing will show.

**Comment by polarwinkel** [comment]
oh and: you get a `Thanks, it worked` back if it succeeds, maybe I'll integrate error messages later if it fails, but I have no real testing yet (only if `teachers` or `students` is missing, but not message then yet)

**Comment by TheJKM** [comment]
Container building fails, seems like smbFoldersChanger.py is missing, could you push it?

**Comment by polarwinkel** [comment]
sorry, I forgot to add it in git, fixed

**Comment by TheJKM** [comment]
Should work now

**Comment by polarwinkel** [comment]
Thanks, I just tested it, all seems to be working fine!
