### ISSUE TITLE
Custom samba groupfolders reset to default after server reboot

### ISSUE THREAD

**Issue by TheJKM** [polarwinkel/SchoolConnect#23]
Sorry, another one of this type, but might have the same cause: After a server reboot, the samba configuration file (/etc/samba/smb.conf) is reset to the default template shipped with the container. So, connecting to private folders is still possible, but the groupfolders are gone.

**Comment by polarwinkel** [comment]
wasn't "that type", just a becreated config from settings.env on container start.

fixed
