### ISSUE TITLE
Database Error after update

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#24]
After the update from a version without the groupfolder-edit-function there is a `ERR_DATABASE_ERROR` when adding a group folder.
Could you add a button "Create default" to create the necessary tables and add the [old config](https://github.com/philleconnect/ServerContainers/blob/master/samba/smbFolders)?

**Comment by polarwinkel** [comment]
#Workaround:
creating it manually worked:
```
CREATE TABLE IF NOT EXISTS groupfolders (id int(11) NOT NULL, name text COLLATE utf8_bin NOT NULL, students int(11) NOT NULL, teachers int(11) NOT NULL, roomexchange int(11) NOT NULL, writeable int(11) NOT NULL, path text COLLATE utf8_bin NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
and then
```
ALTER TABLE groupfolders ADD PRIMARY KEY (id);
ALTER TABLE groupfolders MODIFY id int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;
```
Now I can create the Folders manually.

**Comment by polarwinkel** [comment]
Just all the config profiles are broken now: The group folders all say "undefined".
I guess that changed to the db-key?
The easiest might be to just reconfigure the profiles by hand...

**Comment by TheJKM** [comment]
Working on it... won't fix broken config profiles as I think there aren't many installations out there yet.

**Comment by polarwinkel** [comment]
Yep, that's fine. I reconfigured the groupfolders already, that was quickly done, and all is working perfectly.

**Comment by TheJKM** [comment]
Added database update in latest pc_admin update. I extended your concept a bit:
In `api/versioncode.php` I store the version code (just an integer) of the actual installed version.
On every login I check if the version code in `config/config.txt` is the same or lower. If it's lower I redirect to up/postupdate.php, which will do the required updates depending on the existing version code.
The actual version code is 2, and it detects installations without any version code as 1.
Notice that the update will fail if the groupfolders-table is already existing. In this case I recommend a simple one-time script like this (`pseudoupdate.php`):
`<?php`
`include "api/accessConfig.php";`
`include "api/versioncode.php";`
`changeConfigValue('versioncode', false, $versioncode);`
`?>`

**Comment by polarwinkel** [comment]
I guess the detection of code 1 when there is no version code yet has still a problem, on my test I get this error:
```
[error] 378#378: *5 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: versioncode in /var/www/html/api/accessConfig.php on line 64
PHP message: PHP Notice:  Undefined index: versioncode in /var/www/html/api/accessConfig.php on line 67" while reading response header from upstream, client: 172.21.0.1, server: _, request: "GET /ui/postupdate.php?action=doupdate HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "localhost:84", referrer: "http://localhost:84/ui/postupdate.php?action=doupdate"
```
in the logs, and the GUI says "Es ist ein Fehler aufgetreten
Bitte erneut versuchen."

**Comment by TheJKM** [comment]
Works as it should for me. Maybe the groupfolders table already exists is your testing environment? Setup creates it for at least two weeks. However, I just added a simple check so the update won't fail anymore if the table already exists.

**Comment by polarwinkel** [comment]
sorry, you were right, the table was already there in my test system. I forgot that the creation is in dev already for a while.
Works now, thanks again.
