### ISSUE TITLE
Drive: List out of Bounce verhindert login

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#4]
An den Netbooks:
Ein Fehler "Linst index out of Bounce", bei dem er wohl durch einen Timeout die Nutzerliste nicht laden kann, verhindert ein einbinden der Laufwerke.
Nach dem Schließen und wieder öffnen von Drive sind die Laufwerke ohne neue Eingabe des Benutzers da!

**Comment by TheJKM** [comment]
Wird mit dem allgemeinen Timeout-Fix behoben sein.
