### ISSUE TITLE
Import of new list of students

### ISSUE THREAD

**Issue by polarwinkel** [polarwinkel/SchoolConnect#9]
The Import-function for new Students should get a list of all students at the school and compare them to the students already in the LDAP.
Then it should have an option to
- import all, where given- and family name as well as date of birth are equal
- give an option (i.e. checkboxes) to import students where two of the above are equal
- give an option for other "new" students to be marked as another "drop-out"-students (if i.e. date of birth and Name has been corrected)
- drop students that are not at the school any more (including deletion/moving of folders) and import new students, creating the necessary folders in samba

**Comment by TheJKM** [comment]
Done. Some rare cases (e.g. evil twins) not working yet.

**Comment by polarwinkel** [comment]
I integrated it in the dev-branch and am just testig it.
There are 2 little issues I just found:
- The csv-Import (the new surface looks great!) has problems when there is a "&"-character in the password, could you check this?
- an option to keep old accounts even if they are not in the csv will be necessary. Could you add an option to drop old accounts from the deletion list?

And: When I change two things of a student (i.e. date of birth and name) there is no chance to connect those manually. But I don't have a good idea how to make it - probably a input field where I can enter a number in the deletion list and the "new accounts"-list, and if those numbers match the old account will be transferred to the new one?

**Comment by polarwinkel** [comment]
oh, and: The german umlaut "ü" in a student name is translated to "u" instead of "ue"

**Comment by polarwinkel** [comment]
and a "Finished" message woud be nice. If I am not looking at the symbols carefully I would click "Änderungen Übernehmen" once more and get an error for the deletions, since they are deleted already.

**Comment by TheJKM** [comment]
Keep old accounts and umlaute are done. "&" seems to be caused by LDAP, because manual account creation also fails. There should be a finished message, for me it's working (tested in Safari - but it's the same type of message as in the whole system)

**Comment by TheJKM** [comment]
All remaining bugs are now fixed.

**Comment by polarwinkel** [comment]
Thanks!
I integrated it in the container, when doing rough testing all seems to work now.
I'll merge it with master and roll out at the school in when we have the samba-config working.
